name: news_app
description: "A new Flutter project."

# This line prevents the package from being accidentally published to pub.dev
# using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

# Specify the Dart SDK version
environment:
  sdk: ">=3.5.4 <4.0.0"  # specify a valid version range for Dart SDK

dependencies:
  flutter:
    sdk: flutter

  # Add the necessary dependencies for your app
  cupertino_icons: ^1.0.8  # For iOS-style icons
  http: ^1.2.2  # Add this if you plan on making HTTP requests
  cached_network_image: ^3.4.1  # Caching images
  webview_flutter: ^4.10.0  # WebView plugin for displaying web content

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Recommended linting for best practices

# For information on the generic Dart part of this file, see the following page:
# https://dart.dev/tools/pub/pubspec

# Flutter section
flutter:
  uses-material-design: true  # Enables Material Design widgets

  # Add assets (images, etc.) if necessary
  assets:
    - assets/images/  # Path to any assets folder you may have

  # To add custom fonts to your application (if any):
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
